-- Chạy đoạn này trong Supabase > SQL Editor > Run

create table if not exists projects (
    id bigint generated by default as identity primary key,
    code text not null unique,
    name text not null,
    description text,
    drive_folder_id text,
    drive_folder_url text,
    created_at timestamp with time zone default now()
);

create table if not exists excel_files (
    id bigint generated by default as identity primary key,
    project_id bigint references projects(id) on delete cascade,
    file_name text,
    file_type text default 'excel',
    drive_file_id text,
    drive_file_url text,
    row_count integer default 0,
    uploaded_at timestamp with time zone default now()
);

create table if not exists materials (
    id bigint generated by default as identity primary key,
    project_id bigint references projects(id) on delete cascade,
    excel_file_id bigint references excel_files(id) on delete set null,
    sheet_name text,
    excel_row integer,
    item_no text,
    material_code text,
    material_name text,
    specification text,
    unit text,
    quantity text,
    supplier text,
    po_no text,
    request_date text,
    required_date text,
    note text,
    location text,
    responsible text,
    actual_date text,
    is_ordered boolean default false,
    extra_json jsonb,
    created_at timestamp with time zone default now(),
    updated_at timestamp with time zone default now()
);

-- Nếu bạn đã tạo bảng bằng đoạn SQL cũ, chạy thêm các dòng ALTER này vẫn an toàn.
alter table projects add column if not exists drive_folder_id text;
alter table projects add column if not exists drive_folder_url text;

alter table excel_files add column if not exists file_type text default 'excel';
alter table excel_files add column if not exists drive_file_id text;
alter table excel_files add column if not exists drive_file_url text;
alter table excel_files add column if not exists row_count integer default 0;

alter table materials add column if not exists excel_file_id bigint references excel_files(id) on delete set null;
alter table materials add column if not exists sheet_name text;
alter table materials add column if not exists excel_row integer;
alter table materials add column if not exists request_date text;
alter table materials add column if not exists required_date text;
alter table materials add column if not exists location text;
alter table materials add column if not exists responsible text;
alter table materials add column if not exists actual_date text;
alter table materials add column if not exists extra_json jsonb;
alter table materials add column if not exists updated_at timestamp with time zone default now();

-- Lưu token Google OAuth của tài khoản Drive đã cấp quyền cho app.
create table if not exists app_settings (
    key text primary key,
    value jsonb,
    updated_at timestamp with time zone default now()
);

-- App hiện chưa có đăng nhập riêng, nên tắt RLS để API publishable key thao tác được.
alter table public.projects disable row level security;
alter table public.materials disable row level security;
alter table public.excel_files disable row level security;
alter table public.app_settings disable row level security;
